In [2]:
import numpy as np

In [3]:
# np 从一个 python 序列中进行初始化
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
# np 的视图
b = a[2:4]
b

array([3, 4])

In [5]:
b[0] = 7
a

array([1, 2, 7, 4, 5, 6])

In [8]:
# 翻转
b[::-1]
b

array([7, 4])

In [11]:
# 创建 np.array 必须是一个序列
# a = np.array([1, 2, 3], [4, 5, 6], [7, 8, 9])
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# 访问第二行第三列
# 这样思考，列是最后一个，行是倒数第二个
a[1,2]

np.int64(6)

In [15]:
# 下面查看数组的属性
# 维度，形状，大小
a.ndim

2

In [16]:
a.shape

(3, 3)

In [17]:
a.ndim == len(a.shape)

True

In [18]:
a.size

9

In [19]:
import math
# prod 是一个用于计算可迭代对象(如列表、元组)中所有元素的积的函数 从 3.8 中引入
a.size == math.prod(a.shape)

True

In [21]:
# 创建数组
# 用 0 填充
a = np.zeros(7)
a

array([0., 0., 0., 0., 0., 0., 0.])

In [22]:
# 用 1 填充
a = np.ones(7)
a

array([1., 1., 1., 1., 1., 1., 1.])

In [23]:
# 随即数值，基于当前的内存状态，快速
a = np.empty(7)
a

array([1., 1., 1., 1., 1., 1., 1.])

In [26]:
# 按照范围进行
# arange 是 array(数组) range(范围)
# np.arange(start, end, step)
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [28]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [33]:
# linear space 在指定范围空间内生成均匀分布的数值
# numpy.linespace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# retstep 返回值中是否包含生成的数值和步长
# dtype 输出数组的数据类型
a = np.linspace(1, 10, 7)
a

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [34]:
a = np.linspace(1, 10, 7, retstep=True)
a

(array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ]), np.float64(1.5))

In [35]:
# 指定数据类型
a = np.ones(4, dtype=np.int64)
a

array([1, 1, 1, 1])

In [4]:
a = np.array([1, 2])
a

array([1, 2])

In [5]:
a = np.stack(a).T
a

array([1, 2])